version: '3'

dotenv: ['.env']

tasks:
  docker:up:
    desc: Run the Docker container for GD Tachometer
    dir: docker
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose-db.yml build
      - docker compose -f docker-compose.yml -f docker-compose-db.yml up

  backend:start:
    desc: Run the backend in development mode (add "-- i" to install dependencies and rebuild postgres image)
    dir: backend
    cmds:
      - |
        {{if eq .CLI_ARGS "i"}} 
        npm install
        docker compose -f ../docker/docker-compose-db.yml build
        {{end}}
      - defer: docker compose -f ../docker/docker-compose-db.yml stop
      - docker compose -f ../docker/docker-compose-db.yml up -d
      - npm run start:dev

  backend:stop:
    desc: Stop the backend containers
    dir: backend
    cmds:
      - docker compose -f ../docker/docker-compose-db.yml stop

  frontend:start:
    desc: Run the frontend in development mode (add "-- i" to install dependencies)
    dir: frontend
    cmds:
      - '{{if eq .CLI_ARGS "i"}}npm install{{end}}'
      - npm run start
  
  images:list:
    desc: List all Docker images
    silent: true
    vars:
      GHCR_TOKEN:
        sh: echo -n '{{.ghcr_token}}' | base64
      REPO: ilmandone/gd-tachometer
      GHCR_OUTPUT:
        sh: curl -H "Authorization{{":"}} Bearer {{.GHCR_TOKEN}}" https://ghcr.io/v2/{{.REPO}}/tags/list --no-progress-meter
    cmds:
      - echo "Show all available tags for the repository {{.REPO}}"
      - jq '.tags[]' <<< '{{.GHCR_OUTPUT}}'
