version: '3'

tasks:
  docker:up:
    desc: Run the Docker container for GD Tachometer
    dir: docker
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose-db.yml build
      - docker compose -f docker-compose.yml -f docker-compose-db.yml up

  backend:start:
    desc: Run the backend in development mode (add "-- i" to install dependencies and rebuild postgres image)
    dir: backend
    cmds:
      - |
        {{if eq .CLI_ARGS "i"}} 
        npm install
        docker compose -f ../docker/docker-compose-db.yml build
        {{end}}
      - defer: docker compose -f ../docker/docker-compose-db.yml stop
      - docker compose -f ../docker/docker-compose-db.yml up -d
      - npm run start:dev

  backend:stop:
    desc: Stop the backend containers
    dir: backend
    cmds:
      - docker compose -f ../docker/docker-compose-db.yml stop

  frontend:start:
    desc: Run the frontend in development mode (add "-- i" to install dependencies)
    dir: frontend
    cmds:
      - '{{if eq .CLI_ARGS "i"}}npm install{{end}}'
      - npm run start
  
  