services:
  postgres:
    container_name: postgres
    build: ./postgres
    ports:
      - "5435:5432"
    volumes:
      - dg-postgres-data:/var/lib/postgresql-static/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-gddb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
    networks:
      - dg-dev
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
        interval: 5s
        timeout: 5s
        retries: 5

volumes:
  dg-postgres-data:
    labels:
      dg.volume: dg-postgres-data

networks:
  dg-dev:
    name: dg-dev-network
